---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dkndr6aqy52d/public_html/
    - /bin/cp -a osrevenge/OSRevenge/dist/osrevenge/. $DEPLOYPATH # Copy the OSRevenge folder to the public_html folder
  