---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dkndr6aqy52d/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp gittest.html $DEPLOYPATH
    - /bin/cp wiki.html $DEPLOYPATH
    - /bin/cp wikimd.html $DEPLOYPATH
  